base_url = "https://ipfs-blog.wgb5445.cc"
compile_sass = true

title = "Brief theme"
description = "A brief blog theme"
generate_feed = true

taxonomies = [
    { name = "blockchain", feed = true},
    { name = "css", feed = true},
    { name = "docker", feed = true},
]

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

[extra]
author="不霁何虹"
description="A brief blog theme"
brief_favicon="https://arweave.net/mFFcgeIoLnhzQDYAHTYHkQ1eEYVwO9XvU7GitAUnq4U"
brief_sticky = true
brief_reverse = false
brief_theme = ""
brief_links = [
    {url = "https://google.com", name = "About"},
]
brief_menus = [
    {url = "",name = "Home"},
    {url = "archives",name = "Archives"},
    {url = "tags",name = "Tags"},
    {url = "categories",name = "Categories"},
    {url = "link",name = "Link"},
    {url = "about",name = "About"},
]
